name: Go

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23

    - name: Build
      working-directory: ./cmd/scalecloud.de-api
      run: go build -v ./...

    - name: Test
      working-directory: ./cmd/scalecloud.de-api
      run: go test -v ./...
